BEGIN;
DROP TABLE IF EXISTS game;
CREATE TABLE game (
	id BIGSERIAL NOT NULL PRIMARY KEY
);
	
DROP TABLE IF EXISTS round;
CREATE TABLE round (
	id BIGSERIAL NOT NULL PRIMARY KEY
, game_id INTEGER NOT NULL
,	sara INTEGER NOT NULL
,	dorte INTEGER NOT NULL
,	jacob INTEGER NOT NULL
,	martin INTEGER NOT NULL
);

INSERT INTO game DEFAULT VALUES;
COMMIT;
