PORTNAME=	jin

MAINTAINER=	mk@bluepipe.dk
COMMENT=	jin
CATEGORIES=	www devel

RUN_DEPENDS = \
		p5-File-Slurp>0:${PORTSDIR}/devel/p5-File-Slurp \
		p5-JSON>0:${PORTSDIR}/converters/p5-JSON \
		p5-JSON-XS>0:${PORTSDIR}/converters/p5-JSON-XS \
		p5-Plack>0:${PORTSDIR}/www/p5-Plack \
		p5-XML-LibXSLT>0:${PORTSDIR}/textproc/p5-XML-LibXSLT \
		p5-Convert-Color>0:${PORTSDIR}/graphics/p5-Convert-Color \
		p5-Plack-Middleware-Session>0:${PORTSDIR}/www/p5-Plack-Middleware-Session \
		p5-Plack-Middleware-Expires>0:${PORTSDIR}/www/p5-Plack-Middleware-Expires \
		p5-Plack-Middleware-Precompressed>0:${PORTSDIR}/www/p5-Plack-Middleware-Precompressed \
		p5-List-MoreUtils>0:${PORTSDIR}/lang/p5-List-MoreUtils \
		p5-File-Which>0:${PORTSDIR}/sysutils/p5-File-Which \
		p5-IO-Async>0:${PORTSDIR}/devel/p5-IO-Async \
		p5-IPC-Run>0:${PORTSDIR}/devel/p5-IPC-Run \
		p5-HTML-Parser>0:${PORTSDIR}/www/p5-HTML-Parser \
		p5-DateTime>0:${PORTSDIR}/devel/p5-DateTime \
		p5-File-Path>0:${PORTSDIR}/devel/p5-File-Path \
		p5-Mouse>0:${PORTSDIR}/devel/p5-Mouse \
		p5-Any-Moose>0:${PORTSDIR}/devel/p5-Any-Moose \
		p5-Hash-Merge>0:${PORTSDIR}/textproc/p5-Hash-Merge \
		p5-Exception-Class>0:${PORTSDIR}/devel/p5-Exception-Class \
		p5-Devel-CheckOS>0:${PORTSDIR}/devel/p5-Devel-CheckOS \
		p5-Text-MicroTemplate>0:${PORTSDIR}/textproc/p5-Text-MicroTemplate \
		p5-Data-Printer>0:${PORTSDIR}/devel/p5-Data-Printer \
		p5-Class-Load-XS>0:${PORTSDIR}/devel/p5-Class-Load-XS \
		p5-Const-Fast>0:${PORTSDIR}/devel/p5-Const-Fast

# should be in core
#		p5-File-Temp>0:${PORTSDIR}/devel/p5-File-Temp \

#There is dependencies not in ports, use cpanm files

#source builder:
#		${LOCALBASE}/bin/sass:${PORTSDIR}/www/rubygem-haml \
#		${LOCALBASE}/bin/yuicompressor:${PORTSDIR}/www/yuicompressor


.include <bsd.port.pre.mk>

.include <bsd.port.post.mk>
